name: Deploy Chrome Extension
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip extension
        run: |
            zip -r ./dist/extension.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: extension
            path: ./dist/extension.zip

      #- name: Deploy to Chrome Web Store
      #  uses: wei/chrome-web-store-upload-action@v1.1.0
      #  with:
      #    extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
      #    client-id: ${{ secrets.CHROME_CLIENT_ID }}
      #    client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      #    refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      #    zip-file: ./dist/extension.zip